import { createFileRoute, Link } from "@tanstack/react-router";
import { useMemo, useState } from "react";
import {
  Calendar,
  Copy,
  Download,
  FileText,
  Filter,
  MoreHorizontal,
  Sparkles,
  Trash2,
} from "lucide-react";
import { toast } from "sonner";
import { PageHeader } from "@/components/common/PageHeader";
import { PageTransition } from "@/components/common/PageTransition";
import { EmptyState } from "@/components/common/EmptyState";
import { SearchBar } from "@/components/common/SearchBar";
import { ScoreBadge } from "@/components/common/ScoreBadge";
import { Card, CardContent } from "@/components/ui/card";
import { Button } from "@/components/ui/button";
import { Badge } from "@/components/ui/badge";
import {
  Select,
  SelectContent,
  SelectItem,
  SelectTrigger,
  SelectValue,
} from "@/components/ui/select";
import {
  DropdownMenu,
  DropdownMenuContent,
  DropdownMenuItem,
  DropdownMenuSeparator,
  DropdownMenuTrigger,
} from "@/components/ui/dropdown-menu";
import { MOCK_REPORTS, type MockReport } from "@/data/mockReports";
import { cn } from "@/lib/utils";

export const Route = createFileRoute("/_app/reports")({
  head: () => ({
    meta: [
      { title: "Reports — SharanAI" },
      { name: "description", content: "AI-generated recruiter reports." },
    ],
  }),
  component: ReportsCenter,
});

const REC_LABEL: Record<MockReport["recommendation"], { label: string; tone: string }> = {
  strong_hire: { label: "Strong Hire", tone: "bg-success/15 text-success border-success/30" },
  hire: { label: "Hire", tone: "bg-aurora-soft text-aurora-violet border-transparent" },
  lean_hire: { label: "Lean Hire", tone: "bg-amber-500/15 text-amber-600 border-amber-500/30 dark:text-amber-400" },
  no_hire: { label: "No Hire", tone: "bg-destructive/10 text-destructive border-destructive/30" },
};

const STATUS_TONE: Record<MockReport["status"], string> = {
  ready: "bg-success/15 text-success border-success/30",
  processing: "bg-aurora-soft text-aurora-violet border-transparent",
  failed: "bg-destructive/10 text-destructive border-destructive/30",
};

const SESSIONS = Array.from(new Set(MOCK_REPORTS.map((r) => r.ranking_session)));

function ReportsCenter() {
  const [query, setQuery] = useState("");
  const [type, setType] = useState<string>("all");
  const [recommendation, setRecommendation] = useState<string>("all");
  const [session, setSession] = useState<string>("all");
  const [date, setDate] = useState<string>("all");
  const [deleted, setDeleted] = useState<Set<string>>(new Set());

  const filtered = useMemo(() => {
    const now = Date.now();
    const cutoff =
      date === "7"
        ? now - 7 * 86400000
        : date === "30"
          ? now - 30 * 86400000
          : date === "today"
            ? now - 86400000
            : 0;

    return MOCK_REPORTS.filter((r) => !deleted.has(r.id)).filter((r) => {
      if (query) {
        const q = query.toLowerCase();
        const blob = `${r.candidate_name} ${r.candidate_role} ${r.id} ${r.job_title} ${r.ranking_session}`.toLowerCase();
        if (!blob.includes(q)) return false;
      }
      if (type !== "all" && r.type !== type) return false;
      if (recommendation !== "all" && r.recommendation !== recommendation) return false;
      if (session !== "all" && r.ranking_session !== session) return false;
      if (cutoff && new Date(r.generated_at).getTime() < cutoff) return false;
      return true;
    });
  }, [query, type, recommendation, session, date, deleted]);

  const exportCsv = () => {
    const rows = [
      ["Report ID", "Candidate", "Role", "Recommendation", "Match", "Generated", "Session"],
      ...filtered.map((r) => [
        r.id,
        r.candidate_name,
        r.candidate_role,
        REC_LABEL[r.recommendation].label,
        String(r.match_score),
        new Date(r.generated_at).toISOString(),
        r.ranking_session,
      ]),
    ];
    const csv = rows.map((r) => r.map((c) => `"${String(c).replace(/"/g, '""')}"`).join(",")).join("\n");
    const blob = new Blob([csv], { type: "text/csv;charset=utf-8" });
    const url = URL.createObjectURL(blob);
    const a = document.createElement("a");
    a.href = url;
    a.download = `sharanai-reports-${Date.now()}.csv`;
    a.click();
    URL.revokeObjectURL(url);
    toast.success("Exported reports", { description: `${filtered.length} rows` });
  };

  return (
    <PageTransition>
      <PageHeader
        title="Reports"
        description="Browse, filter, and export every AI report generated by Aurora."
        actions={
          <div className="flex flex-wrap gap-2">
            <Button variant="outline" size="sm" onClick={exportCsv} disabled={!filtered.length}>
              <Download className="mr-1.5 h-3.5 w-3.5" /> Export
            </Button>
            <Button asChild size="sm" className="bg-aurora text-primary-foreground hover:opacity-90">
              <Link to="/ranking">
                <Sparkles className="mr-1.5 h-3.5 w-3.5" /> New ranking
              </Link>
            </Button>
          </div>
        }
      />

      <Card className="shadow-elegant">
        <CardContent className="grid gap-3 p-4 md:grid-cols-[minmax(0,1fr)_auto_auto_auto_auto] md:items-center">
          <SearchBar
            value={query}
            onChange={setQuery}
            placeholder="Search candidates, report IDs, sessions…"
            aria-label="Search reports"
          />
          <Select value={date} onValueChange={setDate}>
            <SelectTrigger className="h-9 w-full md:w-[150px]">
              <Calendar className="mr-1.5 h-3.5 w-3.5 text-muted-foreground" />
              <SelectValue placeholder="Date" />
            </SelectTrigger>
            <SelectContent>
              <SelectItem value="all">Any time</SelectItem>
              <SelectItem value="today">Last 24h</SelectItem>
              <SelectItem value="7">Last 7 days</SelectItem>
              <SelectItem value="30">Last 30 days</SelectItem>
            </SelectContent>
          </Select>
          <Select value={type} onValueChange={setType}>
            <SelectTrigger className="h-9 w-full md:w-[150px]">
              <Filter className="mr-1.5 h-3.5 w-3.5 text-muted-foreground" />
              <SelectValue placeholder="Type" />
            </SelectTrigger>
            <SelectContent>
              <SelectItem value="all">All types</SelectItem>
              <SelectItem value="full">Full report</SelectItem>
              <SelectItem value="screening">Screening</SelectItem>
              <SelectItem value="technical">Technical</SelectItem>
              <SelectItem value="executive">Executive</SelectItem>
            </SelectContent>
          </Select>
          <Select value={recommendation} onValueChange={setRecommendation}>
            <SelectTrigger className="h-9 w-full md:w-[160px]">
              <SelectValue placeholder="Recommendation" />
            </SelectTrigger>
            <SelectContent>
              <SelectItem value="all">All recs</SelectItem>
              <SelectItem value="strong_hire">Strong Hire</SelectItem>
              <SelectItem value="hire">Hire</SelectItem>
              <SelectItem value="lean_hire">Lean Hire</SelectItem>
              <SelectItem value="no_hire">No Hire</SelectItem>
            </SelectContent>
          </Select>
          <Select value={session} onValueChange={setSession}>
            <SelectTrigger className="h-9 w-full md:w-[200px]">
              <SelectValue placeholder="Session" />
            </SelectTrigger>
            <SelectContent>
              <SelectItem value="all">All sessions</SelectItem>
              {SESSIONS.map((s) => (
                <SelectItem key={s} value={s}>
                  {s}
                </SelectItem>
              ))}
            </SelectContent>
          </Select>
        </CardContent>
      </Card>

      <div className="mt-5 flex items-center justify-between">
        <p className="text-xs text-muted-foreground">
          {filtered.length} of {MOCK_REPORTS.length - deleted.size} reports
        </p>
      </div>

      {filtered.length === 0 ? (
        <Card className="mt-3 shadow-elegant">
          <CardContent className="p-8">
            <EmptyState
              icon={FileText}
              title="No reports match your filters"
              description="Try clearing filters or generating a new ranking session."
              action={
                <Button asChild size="sm" className="bg-aurora text-primary-foreground hover:opacity-90">
                  <Link to="/ranking">Start a ranking</Link>
                </Button>
              }
            />
          </CardContent>
        </Card>
      ) : (
        <ul className="mt-3 grid grid-cols-1 gap-3 lg:grid-cols-2 xl:grid-cols-3">
          {filtered.map((r) => (
            <ReportCard
              key={r.id}
              report={r}
              onDelete={() => {
                setDeleted((prev) => new Set(prev).add(r.id));
                toast.success("Report deleted", { description: r.id });
              }}
            />
          ))}
        </ul>
      )}
    </PageTransition>
  );
}

function ReportCard({ report, onDelete }: { report: MockReport; onDelete: () => void }) {
  const rec = REC_LABEL[report.recommendation];

  const copy = async () => {
    await navigator.clipboard.writeText(`${report.id} — ${report.candidate_name} (${report.job_title})`);
    toast.success("Copied report reference");
  };

  return (
    <li className="group relative overflow-hidden rounded-xl border border-border bg-card p-4 shadow-elegant transition-all hover:border-aurora-violet/40">
      <div className="flex items-start justify-between gap-3">
        <div className="min-w-0">
          <div className="flex items-center gap-2">
            <Badge variant="outline" className={cn("font-mono text-[10px]", STATUS_TONE[report.status])}>
              {report.status}
            </Badge>
            <span className="font-mono text-[10px] text-muted-foreground">{report.id}</span>
          </div>
          <h3 className="mt-2 truncate font-display text-base font-semibold tracking-tight">
            {report.candidate_name}
          </h3>
          <p className="truncate text-xs text-muted-foreground">{report.candidate_role}</p>
        </div>
        <ScoreBadge value={report.match_score} />
      </div>

      <div className="mt-3 flex flex-wrap items-center gap-1.5">
        <Badge variant="outline" className={cn("text-[10px]", rec.tone)}>
          {rec.label}
        </Badge>
        <Badge variant="outline" className="bg-surface text-[10px] capitalize">
          {report.type}
        </Badge>
        <Badge variant="outline" className="bg-surface text-[10px]">
          {report.generated_label}
        </Badge>
      </div>

      <p className="mt-3 line-clamp-2 text-xs leading-relaxed text-muted-foreground">
        {report.executive_summary}
      </p>

      <div className="mt-2.5 truncate text-[11px] text-muted-foreground">
        Session · {report.ranking_session}
      </div>

      <div className="mt-4 flex items-center gap-2">
        {report.status === "ready" ? (
          <Button asChild size="sm" className="h-8 flex-1 bg-aurora text-primary-foreground hover:opacity-90">
            <Link to="/reports/$id" params={{ id: report.id }}>
              Open
            </Link>
          </Button>
        ) : (
          <Button size="sm" disabled className="h-8 flex-1 opacity-60">
            {report.status === "processing" ? "Processing…" : "Failed"}
          </Button>
        )}
        <Button size="sm" variant="outline" className="h-8" onClick={copy} aria-label="Copy reference">
          <Copy className="h-3.5 w-3.5" />
        </Button>
        <DropdownMenu>
          <DropdownMenuTrigger asChild>
            <Button size="sm" variant="outline" className="h-8" aria-label="More actions">
              <MoreHorizontal className="h-3.5 w-3.5" />
            </Button>
          </DropdownMenuTrigger>
          <DropdownMenuContent align="end" className="w-44">
            <DropdownMenuItem onClick={() => toast("PDF export coming soon")}>
              <Download className="mr-2 h-3.5 w-3.5" /> Download PDF
            </DropdownMenuItem>
            <DropdownMenuItem onClick={() => toast.success("Markdown downloaded")}>
              <Download className="mr-2 h-3.5 w-3.5" /> Download Markdown
            </DropdownMenuItem>
            <DropdownMenuItem onClick={copy}>
              <Copy className="mr-2 h-3.5 w-3.5" /> Copy reference
            </DropdownMenuItem>
            <DropdownMenuSeparator />
            <DropdownMenuItem className="text-destructive focus:text-destructive" onClick={onDelete}>
              <Trash2 className="mr-2 h-3.5 w-3.5" /> Delete report
            </DropdownMenuItem>
          </DropdownMenuContent>
        </DropdownMenu>
      </div>
    </li>
  );
}
