import { createFileRoute, Link } from "@tanstack/react-router";
import { useEffect, useMemo, useState } from "react";
import {
  Calendar,
  Copy,
  Download,
  FileText,
  Filter,
  MoreHorizontal,
  Sparkles,
  Trash2,
} from "lucide-react";
import { toast } from "sonner";
import { PageHeader } from "@/components/common/PageHeader";
import { PageTransition } from "@/components/common/PageTransition";
import { EmptyState } from "@/components/common/EmptyState";
import { SearchBar } from "@/components/common/SearchBar";
import { ScoreBadge } from "@/components/common/ScoreBadge";
import { Card, CardContent } from "@/components/ui/card";
import { Button } from "@/components/ui/button";
import { Badge } from "@/components/ui/badge";
import {
  Select,
  SelectContent,
  SelectItem,
  SelectTrigger,
  SelectValue,
} from "@/components/ui/select";
import {
  DropdownMenu,
  DropdownMenuContent,
  DropdownMenuItem,
  DropdownMenuSeparator,
  DropdownMenuTrigger,
} from "@/components/ui/dropdown-menu";
import { reportService } from "@/services/report.service";
import type { Report } from "@/types";
import { cn } from "@/lib/utils";

export const Route = createFileRoute("/_app/reports")({
  head: () => ({
    meta: [
      { title: "Reports — SharanAI" },
      { name: "description", content: "AI-generated recruiter reports." },
    ],
  }),
  component: ReportsCenter,
});

// const REC_LABEL: Record<MockReport["recommendation"], { label: string; tone: string }> = {
//   strong_hire: { label: "Strong Hire", tone: "bg-success/15 text-success border-success/30" },
//   hire: { label: "Hire", tone: "bg-aurora-soft text-aurora-violet border-transparent" },
//   lean_hire: { label: "Lean Hire", tone: "bg-amber-500/15 text-amber-600 border-amber-500/30 dark:text-amber-400" },
//   no_hire: { label: "No Hire", tone: "bg-destructive/10 text-destructive border-destructive/30" },
// };

// const STATUS_TONE: Record<MockReport["status"], string> = {
//   ready: "bg-success/15 text-success border-success/30",
//   processing: "bg-aurora-soft text-aurora-violet border-transparent",
//   failed: "bg-destructive/10 text-destructive border-destructive/30",
// };

// const SESSIONS = Array.from(new Set(MOCK_REPORTS.map((r) => r.ranking_session)));

function ReportsCenter() {
  const [query, setQuery] = useState("");
  const [type, setType] = useState<string>("all");
  const [recommendation, setRecommendation] = useState<string>("all");
  const [session, setSession] = useState<string>("all");
  const [date, setDate] = useState<string>("all");
  const [deleted, setDeleted] = useState<Set<string>>(new Set());
  const [reports, setReports] = useState<Report[]>([]);
  const [loading, setLoading] = useState(true);

  useEffect(() => {
    async function loadReports() {
      try {
        const data = await reportService.getAll();
        setReports(data);
      } catch (err) {
        console.error(err);
        toast.error("Failed to load reports");
      } finally {
        setLoading(false);
      }
    }

    loadReports();
  }, []);

const filtered = useMemo(() => {
  return reports
    .filter((r) => !deleted.has(r.candidate_id))
    .filter((r) => {
      if (query) {
        const q = query.toLowerCase();

        const blob = `
          ${r.name}
          ${r.headline}
          ${r.current_role}
          ${r.company}
          ${r.country}
        `.toLowerCase();

        if (!blob.includes(q)) return false;
      }

      if (
        recommendation !== "all" &&
        !r.recommendation.toLowerCase().includes(recommendation.toLowerCase())
      ) {
        return false;
      }

      return true;
    });
}, [reports, query, recommendation, deleted]);

  const exportCsv = () => {
  const headers = [
    "Candidate ID",
    "Name",
    "Role",
    "Company",
    "Experience",
    "Country",
    "Score",
    "Recommendation",
  ];

  const rows = filtered.map((r) => [
    r.candidate_id,
    r.name,
    r.current_role,
    r.company,
    r.experience,
    r.country,
    r.profile_score,
    r.recommendation,
  ]);

  const csv = [
    headers,
    ...rows,
  ]
    .map((row) =>
      row
        .map((cell) => `"${String(cell).replace(/"/g, '""')}"`)
        .join(",")
    )
    .join("\n");

  const blob = new Blob([csv], {
    type: "text/csv;charset=utf-8;",
  });

  const url = URL.createObjectURL(blob);

  const a = document.createElement("a");
  a.href = url;
  a.download = `reports-${Date.now()}.csv`;
  a.click();

  URL.revokeObjectURL(url);

  toast.success("Reports exported successfully");
};

  return (
    <PageTransition>
      <PageHeader
        title="Reports"
        description="Browse, filter, and export every AI report generated by Aurora."
        actions={
          <div className="flex flex-wrap gap-2">
            <Button variant="outline" size="sm" onClick={exportCsv} disabled={!filtered.length}>
              <Download className="mr-1.5 h-3.5 w-3.5" /> Export
            </Button>
            <Button asChild size="sm" className="bg-aurora text-primary-foreground hover:opacity-90">
              <Link to="/ranking">
                <Sparkles className="mr-1.5 h-3.5 w-3.5" /> New ranking
              </Link>
            </Button>
          </div>
        }
      />

      <Card className="shadow-elegant">
        <CardContent className="grid gap-3 p-4 md:grid-cols-[minmax(0,1fr)_auto_auto_auto_auto] md:items-center">
          <SearchBar
            value={query}
            onChange={setQuery}
            placeholder="Search candidates, report IDs, sessions…"
            aria-label="Search reports"
          />
          <Select value={date} onValueChange={setDate}>
            <SelectTrigger className="h-9 w-full md:w-[150px]">
              <Calendar className="mr-1.5 h-3.5 w-3.5 text-muted-foreground" />
              <SelectValue placeholder="Date" />
            </SelectTrigger>
            <SelectContent>
              <SelectItem value="all">Any time</SelectItem>
              <SelectItem value="today">Last 24h</SelectItem>
              <SelectItem value="7">Last 7 days</SelectItem>
              <SelectItem value="30">Last 30 days</SelectItem>
            </SelectContent>
          </Select>
          <Select value={type} onValueChange={setType}>
            <SelectTrigger className="h-9 w-full md:w-[150px]">
              <Filter className="mr-1.5 h-3.5 w-3.5 text-muted-foreground" />
              <SelectValue placeholder="Type" />
            </SelectTrigger>
            <SelectContent>
              <SelectItem value="all">All types</SelectItem>
              <SelectItem value="full">Full report</SelectItem>
              <SelectItem value="screening">Screening</SelectItem>
              <SelectItem value="technical">Technical</SelectItem>
              <SelectItem value="executive">Executive</SelectItem>
            </SelectContent>
          </Select>
          <Select value={recommendation} onValueChange={setRecommendation}>
            <SelectTrigger className="h-9 w-full md:w-[160px]">
              <SelectValue placeholder="Recommendation" />
            </SelectTrigger>
            <SelectContent>
              <SelectItem value="all">All recs</SelectItem>
              <SelectItem value="strong_hire">Strong Hire</SelectItem>
              <SelectItem value="hire">Hire</SelectItem>
              <SelectItem value="lean_hire">Lean Hire</SelectItem>
              <SelectItem value="no_hire">No Hire</SelectItem>
            </SelectContent>
          </Select>
          <Select value={session} onValueChange={setSession}>
            <SelectTrigger className="h-9 w-full md:w-[200px]">
              <SelectValue placeholder="Session" />
            </SelectTrigger>
            <SelectContent>
              <SelectItem value="all">All sessions</SelectItem>
              {["All Sessions"].map((s) => (
                <SelectItem key={s} value={s}>
                  {s}
                </SelectItem>
              ))}
            </SelectContent>
          </Select>
        </CardContent>
      </Card>

      <div className="mt-5 flex items-center justify-between">
        <p className="text-xs text-muted-foreground">
          {filtered.length} of {reports.length} reports
        </p>
      </div>

      {filtered.length === 0 ? (
        <Card className="mt-3 shadow-elegant">
          <CardContent className="p-8">
            <EmptyState
              icon={FileText}
              title="No reports match your filters"
              description="Try clearing filters or generating a new ranking session."
              action={
                <Button asChild size="sm" className="bg-aurora text-primary-foreground hover:opacity-90">
                  <Link to="/ranking">Start a ranking</Link>
                </Button>
              }
            />
          </CardContent>
        </Card>
      ) : (
        <ul className="mt-3 grid grid-cols-1 gap-3 lg:grid-cols-2 xl:grid-cols-3">
          {filtered.map((r) => (
            <ReportCard
              key={r.candidate_id}
              report={r}
              onDelete={() => {
                setDeleted((prev) => new Set(prev).add(r.candidate_id));
                toast.success("Report deleted", { description: r.candidate_id });
              }}
            />
          ))}
        </ul>
      )}
    </PageTransition>
  );
}

function ReportCard({
  report,
  onDelete,
}: {
  report: Report;
  onDelete: () => void;
}) {
  const copy = async () => {
    await navigator.clipboard.writeText(
      `${report.candidate_id} — ${report.name}`
    );

    toast.success("Copied report reference");
  };

  return (
    <li className="group relative overflow-hidden rounded-xl border border-border bg-card p-4 shadow-elegant transition-all hover:border-aurora-violet/40">

      <div className="flex items-start justify-between">

        <div>

          <Badge variant="outline">
            {report.candidate_id}
          </Badge>

          <h3 className="mt-3 text-lg font-semibold">
            {report.name}
          </h3>

          <p className="text-sm text-muted-foreground">
            {report.current_role}
          </p>

          <p className="text-xs text-muted-foreground mt-1">
            {report.company}
          </p>

        </div>

        <ScoreBadge value={report.profile_score} />

      </div>

      <div className="mt-4 flex flex-wrap gap-2">

        <Badge variant="secondary">
          {report.recommendation}
        </Badge>

        <Badge variant="outline">
          {report.country}
        </Badge>

      </div>

      <p className="mt-4 text-sm text-muted-foreground line-clamp-3">
        {report.summary}
      </p>

      <div className="mt-5 flex gap-2">

        <Button
          asChild
          size="sm"
          className="flex-1"
        >
          <Link
            to="/reports/$id"
            params={{
              id: report.candidate_id,
            }}
          >
            Open
          </Link>
        </Button>

        <Button
          size="sm"
          variant="outline"
          onClick={copy}
        >
          <Copy className="h-4 w-4" />
        </Button>

        <Button
          size="sm"
          variant="destructive"
          onClick={onDelete}
        >
          <Trash2 className="h-4 w-4" />
        </Button>

      </div>

    </li>
  );
}